website/apps/badgebro/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('website.apps.badgebro.views',
    url(r'^frontdesk/$', 'front_desk', name='front_desk'),

    url(r'^frontdesk/badge/(?P<uid>BA\w{32})/$', 'badge_detail', name='badge_detail'),
    url(r'^frontdesk/badge/(?P<uid>BA\w{32})/upgrade/$', 'badge_upgrade', name='badge_upgrade'),
    url(r'^frontdesk/badge/(?P<uid>BA\w{32})/printed/$', 'badge_printed', name='badge_printed'),
    url(r'^frontdesk/badge/(?P<uid>BA\w{32})/collected/$', 'badge_collected', name='badge_collected'),
    url(r'^frontdesk/badge/(?P<uid>BA\w{32})/print/$', 'badge_print_close', name='badge_print'),

    url(r'^frontdesk/badge/new/$', 'badge_create', name='badge_create'),

    url(r'^frontdesk/order/(?P<order_pk>\d+)/$', 'badge_order_detail', name='badge_order_detail'),
    url(r'^frontdesk/order/(?P<order_pk>\d+)/badge/(?P<uid>BA\w{32})/upgrade/$', 'badge_order_upgrade', name='badge_order_upgrade'),

    url(r'^badgebro/print/(?P<uid>BA\w{32})/$', 'badge_print', name='print'),
    url(r'^badgebro/print/bulk/$', 'badge_print_bulk', name='print_bulk'),
    url(r'^badgebro/print/bulk/(?P<type>\w+)$', 'badge_print_bulk', name='print_bulk'),
    url(r'^badgebro/(?P<uid>BA\w{32})/difference/(?P<ticket_id>\d+)/$', 'badge_difference', name='badge_difference'),

    url(r'^frontdesk/organize/$', 'organize', name='organize'),
    url(r'^frontdesk/organize/(?P<convention>[-\w]+)/badges/$', 'organize_badges', name='organize_badges'),
    url(r'^frontdesk/export/(?P<convention>[-\w]+)/badges/$', 'organize_badges_export', name='organize_badges_export'),
    url(r'^frontdesk/organize/(?P<convention>[-\w]+)/badges/(?P<filter>[-\w]+)/$', 'organize_badges', name='organize_badges'),
    url(r'^frontdesk/export/(?P<convention>[-\w]+)/badges/(?P<filter>[-\w]+)/$', 'organize_badges_export', name='organize_badges_export'),

    url(r'^frontdesk/organize/(?P<convention>[-\w]+)/$', 'organize_events', name='organize_events'),
    url(r'^frontdesk/organize/(?P<convention>[-\w]+)/events/(?P<event>[-\w]+)/$', 'organize_event_registrations', name='organize_event_registrations'),
    url(r'^frontdesk/export/(?P<convention>[-\w]+)/events/(?P<event>[-\w]+)/$', 'organize_event_registrations_export', name='organize_event_registrations_export'),

    url(r'^frontdesk/organize/(?P<convention>[-\w]+)/registrations/$', 'organize_registrations', name='organize_registrations'),
    url(r'^frontdesk/export/(?P<convention>[-\w]+)/registrations/$', 'organize_registrations_export', name='organize_registrations_export'),

)

website/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from mezzanine.core.views import direct_to_template

from cartridge_stripe.forms import OrderForm

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('website.apps.apibro.urls')),

    url(r'^accounts/login/$', 'website.apps.userbro.views.login', name='login'),

    # Shop URLs.
    url(r'^shop/checkout/$', 'cartridge.shop.views.checkout_steps', name='checkout_steps',
        kwargs=dict(form_class=OrderForm)),
    url(r'^shop/', include('cartridge.shop.urls')),
    url(r'^account/orders/$', 'cartridge.shop.views.order_history', name='shop_order_history'),
    url(r'^zebra/', include('zebra.urls',  namespace="zebra",  app_name='zebra')),
    url(r'^profile/', include('website.apps.userbro.urls',  namespace='userbro')),

    url(r'^', include('website.apps.salesbro.urls',  namespace='salesbro')),
    url(r'^', include('website.apps.eventbro.urls',  namespace='eventbro')),
    url(r'^', include('website.apps.badgebro.urls',  namespace='badgebro')),

    # Temporary shop redirect
    url(r'^shop$', RedirectView.as_view(url='tickets/', permanent=False)),

    # Index URL
    url(r'^$', direct_to_template, {'template': 'index.html'}, name='home'),

    # Mezzanine defaults URLs
    (r'^', include('mezzanine.urls')),
)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

if settings.DEBUG and not urlpatterns:
    urlpatterns += staticfiles_urlpatterns()

website/apps/badgebro/api/v1/views.py
from __future__ import unicode_literals, absolute_import

import logging

from rest_framework import status
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from website.apps.badgebro.api.v1 import serializers

logger = logging.getLogger(__name__)


class BadgeAuthenticateView(generics.GenericAPIView):

    serializer_class = serializers.BadgeAuthenticationSerializer
    authentication_classes = (TokenAuthentication, )
    permission_classes = (IsAuthenticated, )

    def post(self, request, *args, **kwargs):
        logger.info(self.request.data)
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            badge = serializer.validated_data['badge']
            badge_serializer = serializers.AuthenticatedBadgeSerializer(instance=badge)

            return Response(badge_serializer.data, status=status.HTTP_200_OK)

        return Response({'detail': 'Invalid badge uid'}, status=status.HTTP_401_UNAUTHORIZED)


auth_badge = BadgeAuthenticateView.as_view()

website/apps/badgebro/views.py
import csv
import logging

from braces.views import GroupRequiredMixin
from cartridge.shop.models import Order
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import JsonResponse, Http404, HttpResponse
from django.shortcuts import get_object_or_404

# Create your views here.
from django.utils import timezone
from django.utils.datetime_safe import datetime
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.views.generic.list import BaseListView
from extra_views import ModelFormSetView

from website.apps.badgebro.forms import BadgeUpdateForm, BadgeUpgradeForm, BadgeCreateForm
from website.apps.badgebro.models import Badge, UpgradeTransaction
from website.apps.eventbro.models import Convention, Event, Registration
from website.apps.salesbro.models import TicketOption

logger = logging.getLogger(__name__)


class FrontDeskListView(GroupRequiredMixin, ListView):
    group_required = u'frontdesk'
    template_name = 'badgebro/frontdesk.html'
    queryset = Badge.objects.all().order_by('order_id').only('order', 'first_name', 'last_name', 'uid')
    paginate_by = 25

    def get_queryset(self):
        query = self.request.GET.get('search')
        queryset = super(FrontDeskListView, self).get_queryset()

        if query:
            if query[:1] == '#':
                queryset = queryset.filter(order__id__iexact=query[1:])
            else:
                filters = Q(first_name__icontains=query)
                filters |= Q(last_name__icontains=query)
                filters |= Q(uid__icontains=query)
                queryset = queryset.filter(filters)

        return queryset


class BadgeDetailView(GroupRequiredMixin, SuccessMessageMixin, UpdateView):
    group_required = u'frontdesk'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'
    form_class = BadgeUpdateForm
    queryset = Badge.objects.all()
    template_name = 'badgebro/badge_detail.html'
    success_message = 'Successfully updated badge'

    def get_success_url(self):
        return reverse('badgebro:badge_detail', kwargs={'uid': self.object.uid})


class BadgeOrderDetailView(GroupRequiredMixin, SuccessMessageMixin, ModelFormSetView):
    group_required = u'frontdesk'
    queryset = Badge.objects.all()
    order_queryet = Order.objects.all()
    form_class = BadgeUpdateForm
    template_name = 'badgebro/badge_order_detail.html'
    model = Badge
    success_message = 'Successfully updated badges'
    extra = 0
    fields = (
        'first_name',
        'last_name',
        'network',
        'type',
        'option'
    )

    def formset_valid(self, formset):

        response = super(BadgeOrderDetailView, self).formset_valid(formset)
        success_message = self.get_success_message({})
        if success_message:
            messages.success(self.request, success_message)

        return response

    def get_order(self):
        queryset = self.order_queryet
        filter_kwargs = {'id': self.kwargs['order_pk']}
        order = get_object_or_404(queryset, **filter_kwargs)
        return order

    def get_queryset(self):
        self.order = self.get_order()
        queryset = super(BadgeOrderDetailView, self).get_queryset()
        filter_kwargs = {'order': self.order}
        queryset = queryset.filter(**filter_kwargs)

        if len(queryset) == 0:
            raise Http404

        return queryset

    def get_context_data(self, **kwargs):
        context = super(BadgeOrderDetailView, self).get_context_data(**kwargs)
        context['order'] = self.order
        return context

badge_order_detail = BadgeOrderDetailView.as_view()


class BadgeUpgradeView(GroupRequiredMixin, SuccessMessageMixin, UpdateView):
    group_required = u'frontdesk'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'
    form_class = BadgeUpgradeForm
    queryset = Badge.objects.select_related('ticket').all()
    template_name = 'badgebro/badge_upgrade.html'
    success_message = 'Successfully upgraded badge'

    def get_success_url(self):
        return reverse('badgebro:badge_detail', kwargs={'uid': self.object.uid})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.get_form(self.get_form_class())

        if form.is_valid():

            old_ticket = self.object.ticket
            new_ticket = form.cleaned_data['new_ticket_option']

            upgrade = UpgradeTransaction()
            upgrade.old_ticket = old_ticket
            upgrade.new_ticket = new_ticket
            upgrade.badge = self.object
            upgrade.payment_method = form.cleaned_data['payment_method']
            upgrade.save()

            return self.form_valid(form=form)

        else:
            return self.form_invalid(form)


class BadgeOrderUgradeView(BadgeUpgradeView):
    group_required = u'frontdesk'

    def get_success_url(self):
        kwargs = {
            'order_pk': self.object.order_id,
        }

        return reverse('badgebro:badge_order_detail', kwargs=kwargs)


def badge_difference(request, uid, ticket_id):

    if not request.user.is_authenticated():
        raise PermissionDenied

    badge_queryset = Badge.objects.select_related('ticket').all()
    ticket_queryset = TicketOption.objects.all()

    badge = get_object_or_404(badge_queryset, uid=uid)
    ticket = get_object_or_404(ticket_queryset, id=ticket_id)

    new_price = int(ticket.price() * 100)
    current_price = int(badge.ticket.price() * 100)

    difference = new_price - current_price

    gst = int(difference * 0.05)

    difference = int(difference) / 100.0
    gst = gst / 100.0

    data = dict()
    data['new_price'] = ticket.price()
    data['difference'] = format(difference, '.2f')
    data['gst'] = format(gst, '.2f')
    data['total'] = format(difference + gst, '.2f')

    return JsonResponse(data=data)


class BadgePrintView(GroupRequiredMixin, DetailView):
    group_required = u'frontdesk'
    queryset = Badge.objects.all()
    template_name = 'badgebro/badge_print.html'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    def get(self, request, *args, **kwargs):

        response = super(BadgePrintView, self).get(request, *args, **kwargs)

        return response


class BadgeBulkPrintView(GroupRequiredMixin, ListView):
    group_required = u'frontdesk'
    queryset = Badge.objects.all()
    ordering = ['order__id']
    template_name = 'badgebro/badge_bulk_print.html'

    def get_queryset(self):
        queryset = super(BadgeBulkPrintView, self).get_queryset()
        queryset = self.check_for_filters(queryset)
        self.mark_printed(queryset)

        return queryset

    def check_for_filters(self, queryset):
        type = None

        if self.kwargs:
            type = self.kwargs['type']

        if type:
            if type == 'special':
                special = ['staff', 'vendor', 'media']
                queryset = queryset.filter(type__in=special)
            else:
                queryset = queryset.filter(type=type)
        else:
            queryset = queryset.filter(user__isnull=False)
            normal = ['Weekend Pass', 'weekend', 'Weekend',
                      'Saturday Pass', 'saturday', 'Saturday',
                      'Sunday Pass', 'sunday', 'Sunday']
            queryset = queryset.filter(type__in=normal)

        return queryset

    def mark_printed(self, queryset):
        for badge in queryset:
            badge.printed = datetime.now()
            badge.save()


class BadgePrintCloseView(BadgePrintView):
    group_required = u'frontdesk'
    queryset = Badge.objects.all()
    template_name = 'badgebro/badge_print_close.html'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'


class BadgeSetPrintedView(GroupRequiredMixin, DetailView):
    group_required = u'frontdesk'
    queryset = Badge.objects.all()
    slug_url_kwarg = 'uid'
    slug_field = 'uid'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.mark_printed()

        return JsonResponse({})


class BadgeSetCollectedView(GroupRequiredMixin, DetailView):
    group_required = u'frontdesk'
    queryset = Badge.objects.all()
    slug_url_kwarg = 'uid'
    slug_field = 'uid'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.mark_collected()
        return JsonResponse({})


class OrganizeListView(GroupRequiredMixin, ListView):
    group_required = u'frontdesk'
    queryset = Convention.objects.all()
    template_name = 'badgebro/organize/conventions.html'

    def get_queryset(self):
        queryset = super(OrganizeListView, self).get_queryset()
        queryset = queryset.order_by('start')
        return queryset


class OrganizeEventListView(GroupRequiredMixin, ListView):
    group_required = u'frontdesk'
    queryset = Event.objects.published()
    convention_queryset = Convention.objects.all()
    ordering = ('event_type', 'start', 'name', )
    template_name = 'badgebro/organize/events.html'

    def get_convention(self):
        queryset = self.convention_queryset
        filter_kwargs = {'slug': self.kwargs['convention']}
        convention = get_object_or_404(queryset, **filter_kwargs)
        return convention

    def get_queryset(self):
        convention = self.get_convention()
        queryset = super(OrganizeEventListView, self).get_queryset()
        filter_kwargs = {'convention': convention}
        queryset = queryset.filter(**filter_kwargs)

        if len(queryset) == 0:
            raise Http404

        return queryset

    def get_context_data(self, **kwargs):
        context = super(OrganizeEventListView, self).get_context_data()
        context['convention'] = self.get_convention()

website/apps/badgebro/templates/badgebro/organize/all_registrations.html
{% extends "base.html" %}

{% block breadcrumb_menu %}
    <li class="active">Organize</li>
{% endblock breadcrumb_menu %}

{% block content %}
    <div class="container">
        {{ object_list }}
    </div>
{% endblock content %}

website/apps/badgebro/templates/badgebro/organize/badges.html
{% extends "base.html" %}

{% block breadcrumb_menu %}
    <li class="active">Organize</li>
{% endblock breadcrumb_menu %}

{% block content %}
    <div class="container">
        {{ object_list }}
    </div>
{% endblock content %}

website/apps/badgebro/templates/badgebro/organize/conventions.html
{% extends "base.html" %}

{% block breadcrumb_menu %}
    <li class="active">Organize</li>
{% endblock breadcrumb_menu %}

{% block content %}
    <div class="container">
        {% for convention in object_list %}
{#                        <a href="{% url "badgebro:organize" %}" class="list-group-item">{{ convention.name }}</a>#}

            <div class="row">
                <div class="col-sm-2">
                    <h3 class="text-center">{{ convention.name }}</h3>
                </div>
                <div class="col-sm-2">
                    <a class="btn btn-default btn-block btn-lg" role="button" href="{% url "badgebro:organize_events" convention=convention.slug %}">Events</a>
                </div>
                <div class="col-sm-2">
                    <a class="btn btn-default btn-block btn-lg" role="button" href="{% url "badgebro:organize_badges" convention=convention.slug %}">Badges</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

website/apps/badgebro/templates/badgebro/organize/event_registrations.html
{% extends "base.html" %}

{% block breadcrumb_menu %}
    <li><a href="{% url "badgebro:organize" %}">Organize</a></li>
    <li><a href="{% url "badgebro:organize_events" convention=event.convention %}">{{ event.convention.name }} - Events</a></li>
    <li class="active">{{ event.name }}</li>
{% endblock breadcrumb_menu %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">

                {% if confirmed %}
                    <h4>Confirmed</h4>
                    <table class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <td class="text-align-center"><h3>First Name</h3></td>
                                <td class="text-align-center"><h3>Last Name</h3></td>
                                <td class="text-align-center"><h3>Email</h3></td>
                                <td class="text-align-center"><h3>Date Added</h3></td>
                                <td class="text-align-center"><h3>Group Name</h3></td>
                                <td class="text-align-center"><h3>Group Captain</h3></td>
                            </tr>
                        </thead>

                        <tbody>
                            {% for registration in confirmed %}
                            <tr>
                                <td>{{ registration.user.first_name }}</td>
                                <td>{{ registration.user.last_name }}</td>
                                <td>{{ registration.user.email }}</td>
                                <td>{{ registration.date_added }}</td>
                                <td>{{ registration.group_name }}</td>
                                <td>{{ registration.group_captain }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>

                    </table>
                {% else %}
                    <strong>There are no sign ups for this event.</strong>
                {% endif %}

                {% if waitlist %}
                    <h4>Waitlist</h4>
                    <table class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <td class="text-align-center"><h3>First Name</h3></td>
                                <td class="text-align-center"><h3>Last Name</h3></td>
                                <td class="text-align-center"><h3>Email</h3></td>
                                <td class="text-align-center"><h3>Date Added</h3></td>
                                <td class="text-align-center"><h3>Group Name</h3></td>
                                <td class="text-align-center"><h3>Group Captain</h3></td>

                            </tr>
                        </thead>

                        <tbody>

                            {% for registration in waitlist %}
                            <tr>
                                <td>{{ registration.user.first_name }}</td>
                                <td>{{ registration.user.last_name }}</td>
                                <td>{{ registration.user.email }}</td>
                                <td>{{ registration.date_added }}</td>
                                <td>{{ registration.group_name }}</td>
                                <td>{{ registration.group_captain }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
        {{ object_list }}
    </div>
{% endblock content %}

website/apps/badgebro/templates/badgebro/organize/events.html
{% extends "base.html" %}

{% block breadcrumb_menu %}
    <li><a href="{% url "badgebro:organize" %}">Organize</a></li>
    <li class="active">{{ convention.name }} - Events</li>
{% endblock breadcrumb_menu %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-condensed">
                    <thead>
                        <tr>
                            <td class="text-align-center"><h3>Category</h3></td>
                            <td class="text-align-center"><h3>Event</h3></td>
                            <td class="text-align-center"><h3>Date</h3></td>
                            <td class="text-align-center"><h3>Time</h3></td>
                        </tr>
                    </thead>

                    <tbody>
                        {% for event in object_list %}
                        <tr>
                            <td>{{ event.event_type.name }}</td>
                            <td>
                                <a href="{% url "badgebro:organize_event_registrations" convention=event.convention event=event.slug %}">
                                    {{ event.name }}
                                </a>
                            </td>
                            <td>{{ event.start|date }}</td>
                            <td>{{ event.start|time }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

website/apps/badgebro/templates/badgebro/organize/registrations.html
{% extends "base.html" %}

{% block breadcrumb_menu %}
    <li class="active">Organize</li>
{% endblock breadcrumb_menu %}

{% block content %}
    <div class="container">
        {{ object_list }}
    </div>
{% endblock content %}